tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths: [bin/*, tests/*]

checks:
    php:
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        sql_injection_vulnerabilities: true
        side_effects_or_types: true
        useless_calls: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_php_tag_first: true
build:
    dependencies:
        before:
            - composer install --prefer-dist
            - sudo -u postgres createdb yentu_tests
    tests:
        override:
            -
                command: 'phpunit --coverage-clover test.out --configuration tests/config/scrutinizer.xml tests'
                coverage:
                    file: 'test.out'
                    format: 'php-clover'        