tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 600    # Timeout in seconds.    
filter:
    excluded_paths: [bin/*, tests/*]

checks:
    php:
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        sql_injection_vulnerabilities: true
        side_effects_or_types: true
        useless_calls: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_php_tag_first: true
     