language: php
sudo: false
dist: trusty
php:
 - "7.1"
env:
 - YENTU_DRIVER=mysql YENTU_HOST=localhost YENTU_SKIP_SCHEMAS=yes YENTU_USER=root YENTU_BASE_DSN='mysql:host=localhost' COVERAGE=yes
 - YENTU_DRIVER=postgresql YENTU_HOST=localhost YENTU_USER=postgres YENTU_DEFAULT_SCHEMA=public YENTU_BASE_DSN='pgsql:host=localhost' COVERAGE=yes
 - YENTU_DRIVER=sqlite YENTU_FILE=sqlite.db YENTU_SKIP_SCHEMAS=yes YENTU_BASE_DSN='sqlite:sqlite.db' COVERAGE=yes
before_script: 
 - composer install --prefer-dist
  
services:
 - postgresql
 - mysql

script: vendor/bin/phpunit --coverage-clover coverage.clover --configuration tests/config/travis.xml
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --access-token="93e209791d440d1069195255daaa32ce84f96e88ced6d40490b1352dca34f96c" --format=php-clover coverage.clover; fi
